"""add role is_active priority columns

Revision ID: 0c2b62c8fc48
Revises: c262f885592c
Create Date: 2026-08-17 17:16:38.415448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2b62c8fc48'
down_revision: Union[str, Sequence[str], None] = 'c262f885592c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


taskpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority')
userrole = sa.Enum('MEMBER', 'ADMIN', name='userrole')


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    taskpriority.create(bind, checkfirst=True)
    userrole.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', taskpriority, server_default='MEDIUM', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('role', userrole, server_default='MEMBER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
    bind = op.get_bind()
    userrole.drop(bind, checkfirst=True)
    taskpriority.drop(bind, checkfirst=True)
